### PR TITLE
fix: Remove remix-hono dependency

### PR DESCRIPTION
**Pull request by barakcodes**
Removes `remix-hono` as a dependency to allow for a smoother upgrade to react-router 7

### CODE REVIEW

**Comment by yusukebe** [comment]
@barakcodes 

Is this ready for review?

**Comment by barakcodes** [comment]
> @barakcodes
> 
> Is this ready for review?

Fixed formatting it ready now

**Comment by yusukebe** [comment]
@barakcodes 

This is great. Can you resolve the conflict?

**Comment by yusukebe** [comment]
@barakcodes 

Thanks! Let's go.

**Pull request merged**
